include $(RIOTCPU)/msp430_common/Makefile.include

export USEMODULE += periph periph_common uart_stdio libc fmt sytare
export FEATURES_REQUIRED += periph_dma

INCLUDES += -I$(RIOTBASE)/sys/libc/include/gcc
INCLUDES += -I$(RIOTBASE)/sys/libc/include

export CFLAGS += -I$(RIOTCPU)/$(CPU)/elf-gcc/include \
    -fno-common -ffreestanding -nostdinc

export LINKFLAGS += -L$(RIOTCPU)/$(CPU)/elf-gcc/ldscripts \
    -fno-builtin -nostartfiles -nodefaultlibs -nostdlib \
    -T$(CPU_MODEL).ld -lmul_f5
