include $(RIOTCPU)/msp430_common/Makefile.include

export USEMODULE += periph periph_common uart_stdio newlib

export CFLAGS += -I$(RIOTCPU)/$(CPU)/elf-gcc/include
export LINKFLAGS += -L$(RIOTCPU)/$(CPU)/elf-gcc/link
